baseURL = 'http://example.org/'
languageCode = 'en-us'
defaultContentLanguage = "en"
paginate = "7"
title = 'Xelyer'
theme = "spectral"

[params]
fancyTitle = "Xelyer" # title for frontpage, may include image
copyright = "Xelyer"
description = 'A Simple Clean Joke Bot !'
startbuttonText = "Vote me on Top.gg"
startbuttonLink = "https://top.gg/bot/1111316333666254878"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[params.one]
enable = true
title = 'About The Bot  '
body = '''
Xelyerbot is a modern joke bot developed by our team. 
It provides a fun and interactive experience for Discord communities. 
You can check out the bot and its source code on GitHub.
The Best Part is that it is Open Source!.
'''

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Open Source"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Free to code"


[params.two]
enable = true

[[params.two.section]]
img = "img/meme.png"
title = 'Memes!'
body = 'Xelyer will Give you Powerfull meme'

[[params.two.section]]
img = "img/github.png"
title = 'Github Searching'
body = 'Xelyer will search all Github Repo'
[[params.two.section]]
img = "img/joke.png"
title = 'Jokes'
body = 'Xelyer will Gives you Jokes!'


[params.three]
enable = true
title = 'Ready to Contribute'
body = '''
Go to https://github.com/Xelyer To see More info!.<br> Join my Discord Server : https://discord.com/invite/CHUCjdsMnZ
'''